version: 2
jobs:
  build_windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: npm install && ./node_modules/.bin/electron-rebuild
      

workflows:
  version: 2
  build:
    jobs:
      - build_windows