version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:21
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Generate Builds
          command: npm run make
      - store_artifacts:
          path: ~/repo/out/make
